language: python
python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
branches:
  only:
  - master
script:
- python setup.py install && python tests/tciaepxlorer_test.py
env:
  global:
    secure: EoVBXBQHV/uB42IRNcqC7+t9MCGciqpeBeGcanTKYVwU6P/igaL65rq9XB6Bv07Vg2Bg3jJtTZStLgOlY5MWu9+JotN18uYqjSTJp0fNS4E2ezMc8HNWWHFVHE7tpnKTq6JpFKhq5HISNXr9HlCyQvJtqZj8genVO9CnvLmqbOf552uVRow0Hdl5D6RBf5OktM4uOh+EwKSr5SFGf2lrXgeKIlxdvejxPeGXJRHA5NPsNquVmT7Ty7Nn10UnthQumK+Kp3pwBk6piDJpPow8mXaNOnM6ZqtNu6Wuqw+7y17rkXrYmc2tayjtCfjLJJyfSXoDPN8h1bkhh4lf+C8+/gISNtUfWrKyS01j5+K18vL5/R8yd081grAOZRykm+96q4t5XgJedpIWOZ8Nb7PSuKE5F5/HA0gFyDcMg9zjKOt1Ugm2ccHsFPFVbWp+OJHMZVlT7Y8nKGJPl+o8IBVMdM+oy7YoctVrO8jdXgA8ogIK2zdtOQfFntnXk/wEoSzmRaz3BEyGQQcablZ/+nUFjfk1WmFQF/7Hjz/xYEXdI+FK2+Eq5eG+Q2z9fWmN6ux/Go94vidx7BPBqj6jtjMXTm+jT6MimXBCqfOAn/lKGa4qPrM5cP6BwYZzKkdI0NhA2fg+q9+bqjmdqTeZysFjc+VSZSY3hG28PdTxUM2LXlU=
  matrix:
    secure: e4UXQhBBfMfrfRrhgB2U0PcKUmoTOZ2gaFT0yfzBV49KUuR79xel7X7pyLz+rP/6SuQR/w71NNpQt2ZOSD1ORFeAXXw3s4cOeDl14gG/4kByyGOXo2DqFxyeEwXnUl65LuSajM49oCRxV9azrbgz+dGlHXBQccL0wtT3neEXJbrKM7LGuN//kmE/VgwayqoHMhgE5nvggHG43yXiSaPwLWIZFjQWmDzN0ynxX37FPvVPsYKMdwRg3BSHR0QLX9QQUnDSpcoplfuTCOhraIHIlRNpKev1Ydhk9CUZ873sJdruU10724xMSvgbFOlzC2iUZ8kKMO46yPJg6n1NRyAJDi0rJt5BK+T+f7YU8Fipf7QCFATYY5t6GYgEnEPIhT+Y0D/bEU/godqqryH8cWdqVyDCZnw5vohkJc6ENezJqUYqZcLjj0d5f2C1n72jAzsGecaSVmxwbLheygqoK+9xluIPg4cGM+3/pkyR09GhuerrJjJICPW9ER1GiLK2eaWJ9dFP6L92P6xW5mTVwdJJgD4lAM35Dz0sNfuy/cJ7Dakb0yBya6DMDQgVo6YVF6nHNB94x2WbpNwxZtkRkR8lgRrm3tzmNr803YsVeCwV51GxaIQZinRo+fVP7wnMmnfX4IeDN/r/umc9PB+W9IDyMswiWDIdDKaJGusTCRjUNxs=
