language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

branches:
    only:
        - master
#install: "pip install -r requirements.txt"
script: 
    - python setup.py install
    - python tests/tciaepxlorer_test.py

